# Generated by Django 2.2.2 on 2019-06-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('dashboard', '0001_initial'), ('dashboard', '0002_auto_20190618_1203'), ('dashboard', '0003_auto_20190618_1215'), ('dashboard', '0004_auto_20190618_1217'), ('dashboard', '0005_auto_20190618_1253'), ('dashboard', '0006_auto_20190620_0044'), ('dashboard', '0007_auto_20190620_0053'), ('dashboard', '0008_auto_20190620_0054'), ('dashboard', '0009_intervalquerycount_item_mostqueried'), ('dashboard', '0010_auto_20190626_1713'), ('dashboard', '0011_auto_20190626_1715')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=64, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('requester', models.CharField(max_length=512, null=True)),
                ('operation', models.CharField(max_length=64, null=True)),
                ('request_uri', models.CharField(max_length=4096, null=True)),
                ('http_status', models.PositiveSmallIntegerField(null=True)),
                ('error_code', models.CharField(max_length=64, null=True)),
                ('bytes_sent', models.BigIntegerField(null=True)),
                ('object_size', models.BigIntegerField(null=True)),
                ('total_time', models.PositiveIntegerField(null=True)),
                ('turn_around_time', models.PositiveIntegerField(null=True)),
                ('referrer', models.URLField(null=True)),
                ('user_agent', models.CharField(max_length=1024, null=True)),
                ('version_id', models.CharField(max_length=1024, null=True)),
                ('request_id', models.CharField(max_length=64, unique=True)),
                ('s3_key', models.CharField(max_length=256, null=True)),
                ('key_name', models.CharField(db_index=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=128, unique=True)),
                ('experiment', models.CharField(max_length=64)),
                ('assay_title', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
