# Generated by Django 2.2.2 on 2019-06-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_owner', models.BinaryField()),
                ('bucket', models.CharField(max_length=64)),
                ('time', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField()),
                ('requester', models.BinaryField()),
                ('operation', models.CharField(max_length=128)),
                ('request_uri', models.CharField(max_length=2048)),
                ('http_status', models.PositiveSmallIntegerField()),
                ('error_code', models.CharField(max_length=128)),
                ('bytes_sent', models.BigIntegerField()),
                ('object_size', models.BigIntegerField()),
                ('total_time', models.PositiveIntegerField()),
                ('turn_around_time', models.PositiveIntegerField()),
                ('referrer', models.URLField()),
                ('user_agent', models.CharField(max_length=1024)),
                ('version_id', models.CharField(max_length=1024)),
                ('host_id', models.CharField(max_length=1024)),
                ('signature_version', models.PositiveSmallIntegerField(choices=[(0, '-'), (1, 'SigV2'), (2, 'SigV4')])),
                ('cipher_suite', models.CharField(max_length=256)),
                ('auth_type', models.PositiveSmallIntegerField(choices=[(0, '-'), (1, 'AuthHeader'), (2, 'QueryString')])),
                ('host_header', models.URLField()),
                ('tls_version', models.PositiveSmallIntegerField(choices=[(0, '-'), (1, 'TLSv1'), (2, 'TLSv1.1'), (3, 'TLSv1.2')])),
            ],
        ),
    ]
