# Generated by Django 2.2.3 on 2019-07-18 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisLabItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.TextField(max_length=16)),
                ('name', models.TextField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=16, null=True, unique=True)),
                ('pi', models.TextField(max_length=16, null=True)),
                ('project', models.TextField(max_length=8, null=True)),
                ('rfa', models.TextField(max_length=8, null=True)),
                ('status', models.TextField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32, unique=True)),
                ('date_released', models.DateField(null=True)),
                ('assay_title', models.TextField(db_index=True, max_length=8, null=True)),
                ('assay_term_name', models.TextField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('isp', models.TextField(max_length=64)),
                ('country', models.TextField(max_length=32)),
                ('city', models.TextField(max_length=32)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.TextField(max_length=64, unique=True)),
                ('name', models.TextField(max_length=16, unique=True)),
                ('dataset', models.TextField(db_index=True, max_length=16)),
                ('dataset_type', models.TextField(db_index=True, max_length=16)),
                ('file_format', models.TextField(max_length=8, null=True)),
                ('file_type', models.TextField(max_length=8, null=True)),
                ('date_uploaded', models.DateField(null=True)),
                ('award', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Award')),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryCountAtTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.TextField(max_length=16)),
                ('time', models.DateTimeField(db_index=True)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.TextField(max_length=32)),
                ('bucket', models.TextField(max_length=16, null=True)),
                ('time', models.DateTimeField(db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True, null=True)),
                ('requester', models.TextField(db_index=True, max_length=64, null=True)),
                ('request_id', models.TextField(max_length=16, unique=True)),
                ('operation', models.TextField(max_length=16, null=True)),
                ('s3_key', models.TextField(db_index=True, max_length=64, null=True)),
                ('request_uri', models.TextField(max_length=1024, null=True)),
                ('http_status', models.PositiveSmallIntegerField(null=True)),
                ('error_code', models.TextField(db_index=True, max_length=16, null=True)),
                ('bytes_sent', models.BigIntegerField(null=True)),
                ('object_size', models.BigIntegerField(db_index=True, null=True)),
                ('total_time', models.PositiveIntegerField(null=True)),
                ('turn_around_time', models.PositiveIntegerField(null=True)),
                ('referrer', models.URLField(null=True)),
                ('user_agent', models.TextField(max_length=128, null=True)),
                ('version_id', models.TextField(max_length=128, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Lab'),
        ),
    ]
