# Generated by Django 2.2.2 on 2019-06-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='auth_type',
        ),
        migrations.RemoveField(
            model_name='log',
            name='cipher_suite',
        ),
        migrations.RemoveField(
            model_name='log',
            name='host_header',
        ),
        migrations.RemoveField(
            model_name='log',
            name='host_id',
        ),
        migrations.RemoveField(
            model_name='log',
            name='signature_version',
        ),
        migrations.RemoveField(
            model_name='log',
            name='tls_version',
        ),
        migrations.AddField(
            model_name='log',
            name='request_id',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='s3_key',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
