# Generated by Django 2.2.2 on 2019-06-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_squashed_0011_auto_20190626_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='s3_key',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='bucket',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='error_code',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='key_name',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='log',
            name='operation',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='request_id',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='request_uri',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='requester',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='s3_key',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='user_agent',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='version_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
