# Generated by Django 2.2.2 on 2019-06-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190618_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='bucket_owner',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='log',
            name='requester',
            field=models.CharField(max_length=512),
        ),
    ]
