# Generated by Django 2.2.2 on 2019-06-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_querycountattime'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='query_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
