# Generated by Django 2.2.2 on 2019-06-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_item_query_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='requester',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='s3_key',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
