# Generated by Django 2.2.2 on 2019-06-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190618_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='bucket',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='bucket_owner',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='bytes_sent',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='error_code',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='http_status',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='object_size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='operation',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='referrer',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='request_id',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='request_uri',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='requester',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='s3_key',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='total_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='turn_around_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='user_agent',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='version_id',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
