# Generated by Django 2.2.3 on 2019-07-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190722_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='http_status',
            field=models.PositiveSmallIntegerField(db_index=True, null=True),
        ),
    ]
