# Generated by Django 2.2.2 on 2019-06-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190627_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='key_name',
            field=models.CharField(max_length=32),
        ),
    ]
