# Generated by Django 2.2.2 on 2019-06-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190618_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='key_name',
            field=models.CharField(default='Meme', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='request_id',
            field=models.CharField(default='egasgge', max_length=1024),
            preserve_default=False,
        ),
    ]
