# Generated by Django 2.2.2 on 2019-06-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190618_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='bucket_owner',
        ),
        migrations.AlterField(
            model_name='log',
            name='key_name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='log',
            name='request_id',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
