# Generated by Django 2.2.3 on 2019-07-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190723_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='requester_type',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
