# Generated by Django 2.2.2 on 2019-06-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190627_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='assay_title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
