# Generated by Django 2.2.3 on 2019-07-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_log_requester_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='requester_type',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
