# Generated by Django 2.2.3 on 2019-08-01 19:27

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190724_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='error_code',
            field=models.TextField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='http_status',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='object_size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='request_id',
            field=models.TextField(max_length=16),
        ),
        migrations.AlterField(
            model_name='log',
            name='requester',
            field=models.TextField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='requester_type',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='s3_key',
            field=models.TextField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='log',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['item', 'time', 'ip_address', 'requester', 'requester_type', 'request_id', 's3_key', 'http_status', 'error_code', 'object_size'], name='dashboard_l_item_id_7fbb2c_brin'),
        ),
    ]
