# Generated by Django 2.2.2 on 2019-06-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190620_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='request_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
