# Generated by Django 2.2.3 on 2019-07-08 22:00

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Log = apps.get_model('dashboard', 'Log')
    i = 0
    for log in Log.objects.iterator():
        i += 1
        if log.s3_key == 'encode_file_manifest.tsv':
            log.item_name = log.s3_key
        else:
            log.item_name = log.s3_key.split('/')[-1]
        log.save()
        if i % 1000 == 0:
            print(f'{log.item_name}, {log.s3_key}, {i}')


def reverses_func(apps, scema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0008_auto_20190703_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='item_name',
            field=models.CharField(db_index=True, max_length=16, null=True),
        ),
        migrations.RunPython(forwards_func, reverses_func)
    ]
