# Generated by Django 2.2.2 on 2019-06-20 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190620_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalQueryCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=64, unique=True)),
                ('experiment', models.CharField(max_length=64)),
                ('assay_title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MostQueried',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Item')),
            ],
        ),
    ]
