# Generated by Django 2.2.2 on 2019-06-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_intervalquerycount_item_mostqueried'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntervalQueryCount',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='eageg', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='s3_key',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='key_name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.DeleteModel(
            name='MostQueried',
        ),
    ]
