# Generated by Django 2.2.3 on 2019-07-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20190710_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniqueExperimentItemAccess',
        ),
    ]
