# Generated by Django 2.2.3 on 2019-07-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_delete_uniqueexperimentitemaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='querycountattime',
            name='data_set',
            field=models.CharField(default='all', max_length=16),
            preserve_default=False,
        ),
    ]
