# Generated by Django 2.2.3 on 2019-07-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_querycountattime_data_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querycountattime',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
