# Generated by Django 2.2.3 on 2019-07-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20190710_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentitem',
            name='data_set',
            field=models.CharField(default='bernstein', max_length=16),
            preserve_default=False,
        ),
    ]
