# Generated by Django 2.2.3 on 2019-07-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_experimentitem_data_set'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperimentItem',
            new_name='AnalysisLabItem',
        ),
    ]
