# Generated by Django 2.2.3 on 2019-07-12 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20190710_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, null=True, unique=True)),
                ('pi', models.CharField(max_length=16, null=True)),
                ('project', models.CharField(max_length=8, null=True)),
                ('rfa', models.CharField(max_length=8, null=True)),
                ('status', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('date_released', models.DateField(null=True)),
                ('assay_title', models.CharField(db_index=True, max_length=8, null=True)),
                ('assay_term_name', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='assay_title',
        ),
        migrations.RemoveField(
            model_name='item',
            name='query_count',
        ),
        migrations.AddField(
            model_name='item',
            name='date_uploaded',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='file_format',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='file_type',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Experiment'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='award',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Award'),
        ),
        migrations.AddField(
            model_name='item',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Lab'),
        ),
    ]
