# Generated by Django 2.2.3 on 2019-07-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20190711_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dataset',
            field=models.CharField(db_index=True, default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='dataset_type',
            field=models.CharField(db_index=True, default='', max_length=16),
            preserve_default=False,
        ),
    ]
