# Generated by Django 2.2.3 on 2019-07-13 04:34

import django.db.models.deletion
from django.db import migrations, models

from tqdm import tqdm


def forwards_func(apps, schema_editor):
    Log = apps.get_model('dashboard', 'Log')
    Item = apps.get_model('dashboard', 'Item')
    for log in tqdm(Log.objects.iterator(), total=Log.objects.count()):
        try:
            log.item = Item.objects.filter(s3_key=log.s3_key).first()
            log.save()
        except:
            print(f'Error {log.s3_key}')
            log.item = Item.objects.filter()


def reverses_func(apps, scema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0019_auto_20190711_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Item'),
        ),
        migrations.RemoveField(
            model_name='log',
            name='item_name',
        ),
        migrations.RunPython(forwards_func, reverses_func),
    ]
