# Generated by Django 2.2.3 on 2019-07-15 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20190712_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='award',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Award'),
        ),
        migrations.AlterField(
            model_name='item',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Experiment'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Lab'),
        ),
        migrations.AlterField(
            model_name='log',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Item'),
        ),
    ]
